services:
    Harryn\Jacobn\CoreFrameworkBundle\Workflow\Events\:
        resource: '../../../Workflow/Events/*'
        arguments: ['@service_container', '@request_stack', '@doctrine.orm.entity_manager']
        tags:
            - { name: jacobn.automations.workflow.events }
    
    Harryn\Jacobn\CoreFrameworkBundle\Workflow\Actions\:
        resource: '../../../Workflow/Actions/*'
        arguments: ['@service_container', '@request_stack', '@doctrine.orm.entity_manager']
        tags:
            - { name: jacobn.automations.workflow.actions }
    
    Harryn\Jacobn\CoreFrameworkBundle\PreparedResponse\Actions\:
        resource: '../../../PreparedResponse/Actions/*'
        arguments: ['@service_container', '@request_stack', '@doctrine.orm.entity_manager']
        tags:
            - { name: jacobn.automations.prepared_response.actions }
        