services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    # Aliases
    jacobn.service:
        alias: Harryn\Jacobn\CoreFrameworkBundle\Services\UVDeskService
    
    user.provider:
        alias: Harryn\Jacobn\CoreFrameworkBundle\Providers\UserProvider

    user.service:
        alias: Harryn\Jacobn\CoreFrameworkBundle\Services\UserService
    
    email.service:
        alias: Harryn\Jacobn\CoreFrameworkBundle\Services\EmailService
    
    ticket.service:
        alias: Harryn\Jacobn\CoreFrameworkBundle\Services\TicketService
    
    recaptcha.service:
        alias: Harryn\Jacobn\CoreFrameworkBundle\Services\ReCaptchaService

    report.service:
        alias: Harryn\Jacobn\CoreFrameworkBundle\Services\ReportService

    validation.service:
        alias: Harryn\Jacobn\CoreFrameworkBundle\Services\ValidationService

    jacobn.core.file_system.service:
        alias: Harryn\Jacobn\CoreFrameworkBundle\FileSystem\FileSystem
    
    swiftmailer.service:
        alias: Harryn\Jacobn\CoreFrameworkBundle\SwiftMailer\SwiftMailer
    
    jacobn.core.event_dispatcher:
        alias: Harryn\Jacobn\CoreFrameworkBundle\Framework\EventDispatcher
    
    jacobn.extensibles:
        alias: Harryn\Jacobn\CoreFrameworkBundle\Framework\ExtendableComponentManager
